SPELLING_DICT_PATH = 'dict_correct_spelling/'
POSITIVE_NEGATIVE_WORDS_PATH = 'positive_negative_words/'
SLANG_WORDS_DICT_PATH = 'dict_slan_words/'
TRAIN_TEST_PATH = 'train_test_data/'
CLEANED_DATA_PATH = 'cleaned_data/'
GLOVE_EMBEDDING = 'glove_embedding/'
DATA_MODELS = 'models_saving/'
